{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi.fullname" . }}-web
  labels:
    jitsi/component: web
    {{- include "jitsi.labels" . | nindent 4 }}
  {{- with .Values.web.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.web.service.type }}
  {{- $setNodePorts := (or (eq .Values.web.service.type "NodePort") (eq .Values.web.service.type "LoadBalancer")) }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if (and $setNodePorts (not (empty .Values.web.service.nodePort))) }}
      nodePort: {{ .Values.web.service.nodePort }}
      {{- end }}
  selector:
    {{- include "jitsi.selectorLabels" . | nindent 4 }}
    jitsi/component: web
{{- end }}