{{- if and .Values.jvb.enabled .Values.jvb.autoscaling.enabled }}
{{- range $shardName, $shardConfig := .Values.global.shards }}
{{- $fullShardName := include "jitsi.fullShardName" (dict "root" $ "shardName" $shardName) -}}
{{- with $ }}
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $fullShardName }}-jvb
  labels:
    {{- include "jitsi.labels" . | nindent 4 }}
    jitsi/component: jvb
    jitsi/shard: "{{ $shardName }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ $fullShardName }}-jvb
  minReplicas: {{ .Values.jvb.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.jvb.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.jvb.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.jvb.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.jvb.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.jvb.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
