apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jitsi.fullname" . }}
  labels:
    {{- include "jitsi.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.global.secretEnvs }}
  {{- if not (kindIs "invalid" $value) }}
  {{ $key }}: {{ if typeIs "string" $value}}{{ tpl $value $ | b64enc | quote }}{{ else }}{{ $value | b64enc | quote }}{{ end }}
  {{- end }}
  {{- end }}